### ISSUE TITLE
sourcemaps() not defined in rollup.config.js

### ISSUE THREAD

**Issue by norcino** [jim-junior/react-npm-library-template#1]
Hi, first of all thank you for the useful guide.
I was following your guide, and I had to comment sourcemaps() from rollup.config.js, I installed the packages you indicated, my package json is very much similar to yours.
Is there any missing import?

Thanks

**Comment by erikswed** [comment]
Thanks for good Tutorial.
Yea me to commenting out `sourcemaps()` from rollup.config.js, I guess it was not needed for this tutorial something...

**Comment by jim-junior** [comment]
Issue is solved I had not imported the sourcemaps function

**Comment by jim-junior** [comment]
Issue is solved I had not imported the sourcemaps function
